spring.application.name=outboxproducer

# Налаштування сервера додатка
server.port=8081

# З'єднання з базою даних PostgreSQL (Продюсер)
spring.datasource.url=jdbc:postgresql://localhost:5432/test1
spring.datasource.username=test1
spring.datasource.password=test1
spring.jpa.hibernate.ddl-auto=update

# Налаштування Apache Kafka для Продюсера
spring.kafka.bootstrap-servers=localhost:9092

# Серіалізація ключа та значення в стрінгу
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Дозволяємо Spring Boot автоматично активувати шедулер
spring.main.allow-bean-definition-overriding=true
